import { component$ } from '@builder.io/qwik';
import { DocumentHead, Link } from '@builder.io/qwik-city';
import { LanguageFilter, Translation } from '~/components/Translation';

export default component$(() => {
  return (
    <Translation>
      <LanguageFilter  lang='en'>
        <div class="pt-5 w-content col main-axis-center">
          <h1>Privacy Policy</h1>
          <p class="italic">Last updated: Oktober 25, 2025</p>
          <p>This Privacy Policy describes My policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>I use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
            and use of information in accordance with this Privacy Policy.</p>
          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The
            following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <p><strong>Account</strong> means a unique account created for You to access my Service or parts of my
                Service.</p>
            </li>
            <li>
              <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other
                device by a website, containing the details of Your browsing history on that website among its many uses.
              </p>
            </li>
            <li>
              <p><strong>Country</strong> refers to: Sachsen, Germany</p>
            </li>
            <li>
              <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a
                digital tablet.</p>
            </li>
            <li>
              <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
              </p>
            </li>
            <li>
              <p><strong>Service</strong> refers to the Website.</p>
            </li>
            <li>
              <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of me.
                It refers to third-party companies or individuals employed by the Company to facilitate the
                Service, to provide the Service on behalf of me, to perform services related to the Service or to
                assist me in analyzing how the Service is used.</p>
            </li>
            <li>
              <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
                Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </li>
            <li>
              <p><strong>Website</strong> refers to my Personal Website, accessible from <a
                href="https://www.fabianschuster.net" rel="external nofollow noopener"
                target="_blank">https://www.fabianschuster.net</a></p>
            </li>
            <li>
              <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
                entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </li>
          </ul>
          <h2>Collecting and Using Your Personal Data</h2>
          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>While using my Service, I may ask You to provide Me with certain personally identifiable information that can
            be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li>
              <p>Email address</p>
            </li>
            <li>
              <p>First name and last name</p>
            </li>
            <li>
              <p>Usage Data</p>
            </li>
          </ul>
          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of my Service that You visit, the time and date of Your visit, the time spent
            on those pages, unique device identifiers and other diagnostic data.</p>
          <p>When You access the Service by or through a mobile device, I may collect certain information automatically,
            including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address
            of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device
            identifiers and other diagnostic data.</p>
          <p>I may also collect information that Your browser sends whenever You visit my Service or when You access the
            Service by or through a mobile device.</p>
          <h4>Tracking Technologies and Cookies</h4>
          <p>I use Cookies and similar tracking technologies to track the activity on My Service and store certain
            information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to
            improve and analyze My Service. The technologies I use may include:</p>
          <ul>
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can
              instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not
              accept Cookies, You may not be able to use some parts of my Service. Unless you have adjusted Your browser
              setting so that it will refuse Cookies, my Service may use Cookies.</li>
            <li><strong>Web Beacons.</strong> Certain sections of my Service and my emails may contain small electronic
              files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the
              Company, for example, to count users who have visited those pages or opened an email and for other related
              website statistics (for example, recording the popularity of a certain section and verifying system and server
              integrity).</li>
          </ul>
          <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your
            personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close
            Your web browser. Learn more about cookies on the <a
              href="https://www.privacypolicies.com/blog/privacy-policy-template/#Use_Of_Cookies_Log_Files_And_Tracking"
              target="_blank">Privacy Policies website</a> article.</p>
          <p>I use both Session and Persistent Cookies for the purposes set out below:</p>
          <ul>
            <li>
              <p><strong>Necessary / Essential Cookies</strong></p>
              <p>Type: Session Cookies</p>
              <p>Administered by: Me</p>
              <p>Purpose: These Cookies are essential to provide You with services available through the Website and to
                enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user
                accounts. Without these Cookies, the services that You have asked for cannot be provided, and I only use
                these Cookies to provide You with those services.</p>
            </li>
            <li>
              <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
              <p>Type: Persistent Cookies</p>
              <p>Administered by: Me</p>
              <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            </li>
            <li>
              <p><strong>Functionality Cookies</strong></p>
              <p>Type: Persistent Cookies</p>
              <p>Administered by: Me</p>
              <p>Purpose: These Cookies allow me to remember choices You make when You use the Website, such as remembering
                your login details or language preference. The purpose of these Cookies is to provide You with a more
                personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
            </li>
          </ul>
          <h3>Use of Your Personal Data</h3>
          <p>I may use Personal Data for the following purposes:</p>
          <ul>
            <li>
              <p><strong>To provide and maintain my Service</strong>, including to monitor the usage of my Service.</p>
            </li>
            <li>
              <p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal
                Data You provide can give You access to different functionalities of the Service that are available to You
                as a registered user.</p>
            </li>
            <li>
              <p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the
                purchase contract for the products, items or services You have purchased or of any other contract with Me
                through the Service.</p>
            </li>
            <li>
              <p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms
                of electronic communication, such as a mobile application's push notifications regarding updates or
                informative communications related to the functionalities, products or contracted services, including the
                security updates, when necessary or reasonable for their implementation.</p>
            </li>
            <li>
              <p><strong>To manage Your requests:</strong> To attend and manage Your requests to Me.</p>
            </li>
            <li>
              <p><strong>For other purposes</strong>: I may use Your information for other purposes, such as data analysis,
                identifying usage trends, determining the effectiveness of my promotional campaigns and to evaluate and
                improve my Service, products, services, marketing and your experience.</p>
            </li>
          </ul>
          <p>I may share Your personal information in the following situations:</p>
          <ul>
            <li><strong>With Service Providers:</strong> I may share Your personal information with Service Providers to
              monitor and analyze the use of my Service, to contact You.</li>
            <li><strong>With Your consent</strong>: I may disclose Your personal information for any other purpose with
              Your consent.</li>
          </ul>
          <h3>Retention of Your Personal Data</h3>
          <p>I will retain Your Personal Data only for as long as is necessary for the purposes set out in this
            Privacy Policy. I will retain and use Your Personal Data to the extent necessary to comply with my legal
            obligations (for example, if I am required to retain your data to comply with applicable laws), resolve
            disputes, and enforce my legal agreements and policies.</p>
          <p>I will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a
            shorter period of time, except when this data is used to strengthen the security or to improve the functionality
            of my Service, or I are legally obligated to retain this data for longer time periods.</p>
          <h3>Transfer of Your Personal Data</h3>
          <p>Your information, including Personal Data, is processed at my operating offices and in any other
            places where the parties involved in the processing are located. It means that this information may be
            transferred to — and maintained on — computers located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
          <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement
            to that transfer.</p>
          <p>I will take all steps reasonably necessary to ensure that Your data is treated securely and in
            accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or
            a country unless there are adequate controls in place including the security of Your data and other personal
            information.</p>
          <h3>Disclosure of Your Personal Data</h3>
          <h4>Law enforcement</h4>
          <p>Under certain circumstances, I may be required to disclose Your Personal Data if required to do so by
            law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
          <h4>Other legal requirements</h4>
          <p>I may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of me</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
          <h3>Security of Your Personal Data</h3>
          <p>The security of Your Personal Data is important to Me, but remember that no method of transmission over the
            Internet, or method of electronic storage is 100% secure. While I strive to use commercially acceptable means
            to protect Your Personal Data, I cannot guarantee its absolute security.</p>
          <h2>Children's Privacy</h2>
          <p>My Service does not address anyone under the age of 13. I do not knowingly collect personally identifiable
            information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child
            has provided Me with Personal Data, please contact Me. If I become aware that I have collected Personal Data
            from anyone under the age of 13 without verification of parental consent, I take steps to remove that
            information from my servers.</p>
          <p>If I need to rely on consent as a legal basis for processing Your information and Your country requires
            consent from a parent, I may require Your parent's consent before I collect and use that information.</p>
          <h2>Links to Other Websites</h2>
          <p>My Service may contain links to other websites that are not operated by Me. If You click on a third party
            link, You will be directed to that third party's site. I strongly advise You to review the Privacy Policy of
            every site You visit.</p>
          <p>I have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.</p>
          <h2>Changes to this Privacy Policy</h2>
          <p>I may update my Privacy Policy from time to time. I will notify You of any changes by posting the new
            Privacy Policy on this page.</p>
          <p>I will let You know via email and/or a prominent notice on my Service, prior to the change becoming effective
            and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are
            effective when they are posted on this page.</p>
          <h2>Contact Me</h2>
          <p>If you have any questions about this Privacy Policy, You can contact me:</p>
          <ul>
            <li>
              <p>By email: <a href="mailto: contact@fabianschuster.net">contact@fabianschuster.net</a></p>
            </li>
            <li>
              <p>By visiting this page on my website: <Link href="/contact">https://www.fabianschuster.net/contact</Link></p>
            </li>
          </ul>
        </div>
      </LanguageFilter>
      <LanguageFilter lang='de'>
        <div class="pt-5 w-content col main-axis-center">
          <h1>Datenschutzerklärung</h1>
          <p class="italic">Zuletzt aktualisiert: 25. Oktober 2025</p>
          <p>Diese Datenschutzerklärung beschreibt meine Richtlinien und Verfahren zur Erhebung, Nutzung und Offenlegung Ihrer
            Informationen, wenn Sie den Dienst nutzen, und informiert Sie über Ihre Datenschutzrechte und darüber, wie das Gesetz Sie schützt.</p>
          <p>Ich verwende Ihre personenbezogenen Daten, um den Dienst bereitzustellen und zu verbessern. Durch die Nutzung des Dienstes erklären Sie sich mit der Erhebung
            und Nutzung von Informationen in Übereinstimmung mit dieser Datenschutzerklärung einverstanden.</p>

          <h2>Auslegung und Definitionen</h2>
          <h3>Auslegung</h3>
          <p>Begriffe, deren Anfangsbuchstaben großgeschrieben sind, haben die unten festgelegte Bedeutung.
            Die folgenden Definitionen haben dieselbe Bedeutung, unabhängig davon, ob sie im Singular oder Plural auftreten.</p>

          <h3>Definitionen</h3>
          <p>Für die Zwecke dieser Datenschutzerklärung gilt:</p>
          <ul>
            <li>
              <p><strong>Konto</strong> bezeichnet ein eindeutiges Konto, das für Sie erstellt wurde, um auf meinen Dienst oder Teile meines Dienstes zuzugreifen.</p>
            </li>
            <li>
              <p><strong>Cookies</strong> sind kleine Dateien, die auf Ihrem Computer, Mobilgerät oder einem anderen
                Gerät von einer Website gespeichert werden und die Details Ihres Browserverlaufs auf dieser Website enthalten, unter anderem zu verschiedenen Zwecken.</p>
            </li>
            <li>
              <p><strong>Land</strong> bezieht sich auf: Sachsen, Deutschland</p>
            </li>
            <li>
              <p><strong>Gerät</strong> bezeichnet jedes Gerät, das auf den Dienst zugreifen kann, wie z. B. einen Computer, ein Mobiltelefon oder ein Tablet.</p>
            </li>
            <li>
              <p><strong>Personenbezogene Daten</strong> sind alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen.</p>
            </li>
            <li>
              <p><strong>Dienst</strong> bezieht sich auf die Website.</p>
            </li>
            <li>
              <p><strong>Dienstleister</strong> bezeichnet jede natürliche oder juristische Person, die Daten in meinem Auftrag verarbeitet.
                Es bezieht sich auf Drittunternehmen oder Einzelpersonen, die von mir beauftragt werden, den Dienst zu ermöglichen,
                den Dienst in meinem Namen bereitzustellen, dienstbezogene Aufgaben auszuführen oder mir bei der Analyse zu helfen, wie der Dienst genutzt wird.</p>
            </li>
            <li>
              <p><strong>Nutzungsdaten</strong> bezeichnen Daten, die automatisch erfasst werden, entweder durch die Nutzung des Dienstes oder durch die Dienstinfrastruktur selbst (z. B. die Dauer eines Seitenbesuchs).</p>
            </li>
            <li>
              <p><strong>Website</strong> bezieht sich auf meine persönliche Website, erreichbar unter
                <a href="https://www.fabianschuster.net" rel="external nofollow noopener" target="_blank">https://www.fabianschuster.net</a></p>
            </li>
            <li>
              <p><strong>Sie</strong> bezeichnet die natürliche Person, die auf den Dienst zugreift oder ihn nutzt, oder das Unternehmen oder eine andere juristische Person, in deren Namen eine solche Person auf den Dienst zugreift oder ihn nutzt, je nach Fall.</p>
            </li>
          </ul>

          <h2>Erfassung und Nutzung Ihrer personenbezogenen Daten</h2>
          <h3>Arten der erhobenen Daten</h3>
          <h4>Personenbezogene Daten</h4>
          <p>Während der Nutzung meines Dienstes kann ich Sie bitten, mir bestimmte personenbezogene Daten zur Verfügung zu stellen, die verwendet werden können, um Sie zu kontaktieren oder zu identifizieren. Zu den personenbezogenen Daten können gehören, ohne darauf beschränkt zu sein:</p>
          <ul>
            <li><p>E-Mail-Adresse</p></li>
            <li><p>Vor- und Nachname</p></li>
            <li><p>Nutzungsdaten</p></li>
          </ul>

          <h4>Nutzungsdaten</h4>
          <p>Nutzungsdaten werden automatisch bei der Nutzung des Dienstes erfasst.</p>
          <p>Nutzungsdaten können Informationen wie die IP-Adresse Ihres Geräts, den Browsertyp, die Browserversion, die Seiten meines Dienstes, die Sie besuchen, Datum und Uhrzeit Ihres Besuchs, die auf den Seiten verbrachte Zeit, eindeutige Gerätekennungen und andere Diagnosedaten enthalten.</p>
          <p>Wenn Sie auf den Dienst über ein mobiles Gerät zugreifen, kann ich bestimmte Informationen automatisch erfassen, einschließlich, aber nicht beschränkt auf die Art des von Ihnen verwendeten mobilen Geräts, die eindeutige Geräte-ID, die IP-Adresse, das mobile Betriebssystem, den Typ des mobilen Internetbrowsers, eindeutige Gerätekennungen und andere Diagnosedaten.</p>
          <p>Ich kann auch Informationen erfassen, die Ihr Browser sendet, wenn Sie meinen Dienst besuchen oder wenn Sie über ein mobiles Gerät darauf zugreifen.</p>

          <h4>Tracking-Technologien und Cookies</h4>
          <p>Ich verwende Cookies und ähnliche Tracking-Technologien, um Aktivitäten auf meinem Dienst zu verfolgen und bestimmte Informationen zu speichern. Verwendete Tracking-Technologien können Beacons, Tags und Skripte sein, um Informationen zu sammeln und zu verfolgen sowie meinen Dienst zu verbessern und zu analysieren. Die von mir verwendeten Technologien können Folgendes umfassen:</p>
          <ul>
            <li><strong>Cookies oder Browser-Cookies.</strong> Ein Cookie ist eine kleine Datei, die auf Ihrem Gerät gespeichert wird. Sie können Ihren Browser anweisen, alle Cookies abzulehnen oder anzuzeigen, wenn ein Cookie gesendet wird. Wenn Sie Cookies jedoch nicht akzeptieren, können Sie möglicherweise einige Teile meines Dienstes nicht nutzen. Sofern Sie Ihre Browsereinstellungen nicht so angepasst haben, dass Cookies abgelehnt werden, kann mein Dienst Cookies verwenden.</li>
            <li><strong>Web-Beacons.</strong> Bestimmte Abschnitte meines Dienstes und meiner E-Mails können kleine elektronische Dateien enthalten, die als Web-Beacons (auch als Clear GIFs, Pixel-Tags oder Single-Pixel-GIFs bezeichnet) bekannt sind. Diese ermöglichen es mir beispielsweise, Benutzer zu zählen, die diese Seiten besucht oder eine E-Mail geöffnet haben, und andere damit verbundene Website-Statistiken zu erfassen (z. B. die Beliebtheit eines bestimmten Abschnitts und die Überprüfung der System- und Serverintegrität).</li>
          </ul>
          <p>Cookies können „Persistente“ oder „Sitzungs“-Cookies sein. Persistente Cookies verbleiben auf Ihrem Computer oder Mobilgerät, wenn Sie offline gehen, während Sitzungs-Cookies gelöscht werden, sobald Sie Ihren Webbrowser schließen. Weitere Informationen über Cookies finden Sie im Artikel auf der <a href="https://www.privacypolicies.com/blog/privacy-policy-template/#Use_Of_Cookies_Log_Files_And_Tracking" target="_blank">Website Privacy Policies</a>.</p>
          <p>Ich verwende sowohl Sitzungs- als auch persistente Cookies zu den unten genannten Zwecken:</p>

          <ul>
            <li>
              <p><strong>Notwendige / essentielle Cookies</strong></p>
              <p>Typ: Sitzungs-Cookies</p>
              <p>Verwaltet von: Mir</p>
              <p>Zweck: Diese Cookies sind erforderlich, um Ihnen Dienste bereitzustellen, die über die Website verfügbar sind, und um Ihnen die Nutzung bestimmter Funktionen zu ermöglichen. Sie helfen, Benutzer zu authentifizieren und betrügerische Nutzung von Benutzerkonten zu verhindern. Ohne diese Cookies können die von Ihnen angeforderten Dienste nicht bereitgestellt werden. Ich verwende diese Cookies nur, um Ihnen diese Dienste bereitzustellen.</p>
            </li>
            <li>
              <p><strong>Cookies zur Annahme der Cookie-Richtlinie / Hinweise</strong></p>
              <p>Typ: Persistente Cookies</p>
              <p>Verwaltet von: Mir</p>
              <p>Zweck: Diese Cookies identifizieren, ob Benutzer der Verwendung von Cookies auf der Website zugestimmt haben.</p>
            </li>
            <li>
              <p><strong>Funktions-Cookies</strong></p>
              <p>Typ: Persistente Cookies</p>
              <p>Verwaltet von: Mir</p>
              <p>Zweck: Diese Cookies ermöglichen es mir, die von Ihnen getroffenen Entscheidungen bei der Nutzung der Website zu speichern, z. B. Ihre Anmeldedaten oder Sprachpräferenzen. Der Zweck dieser Cookies besteht darin, Ihnen ein persönlicheres Erlebnis zu bieten und zu vermeiden, dass Sie Ihre Präferenzen jedes Mal neu eingeben müssen.</p>
            </li>
          </ul>

          <h3>Verwendung Ihrer personenbezogenen Daten</h3>
          <p>Ich kann personenbezogene Daten für die folgenden Zwecke verwenden:</p>
          <ul>
            <li><p><strong>Zur Bereitstellung und Aufrechterhaltung meines Dienstes</strong>, einschließlich der Überwachung der Nutzung meines Dienstes.</p></li>
            <li><p><strong>Zur Verwaltung Ihres Kontos:</strong> um Ihre Registrierung als Benutzer des Dienstes zu verwalten. Die von Ihnen bereitgestellten personenbezogenen Daten können Ihnen Zugang zu verschiedenen Funktionen des Dienstes verschaffen, die Ihnen als registriertem Benutzer zur Verfügung stehen.</p></li>
            <li><p><strong>Zur Erfüllung eines Vertrags:</strong> zur Entwicklung, Einhaltung und Durchführung des Kaufvertrags über Produkte, Artikel oder Dienstleistungen, die Sie erworben haben, oder eines anderen Vertrags mit mir über den Dienst.</p></li>
            <li><p><strong>Zur Kontaktaufnahme mit Ihnen:</strong> um Sie per E-Mail, Telefonanrufen, SMS oder anderen elektronischen Kommunikationsformen zu kontaktieren, z. B. Push-Benachrichtigungen einer mobilen Anwendung über Aktualisierungen oder informative Mitteilungen zu Funktionen, Produkten oder Dienstleistungen, einschließlich Sicherheitsupdates, wenn dies für deren Umsetzung erforderlich oder angemessen ist.</p></li>
            <li><p><strong>Zur Bearbeitung Ihrer Anfragen:</strong> um Ihre Anfragen an mich zu bearbeiten und zu verwalten.</p></li>
            <li><p><strong>Für andere Zwecke:</strong> Ich kann Ihre Informationen für andere Zwecke verwenden, wie z. B. Datenanalyse, Identifizierung von Nutzungstrends, Bewertung der Wirksamkeit meiner Marketingkampagnen sowie zur Verbesserung meines Dienstes, meiner Produkte, Dienstleistungen, meines Marketings und Ihrer Erfahrung.</p></li>
          </ul>
          <p>Ich kann Ihre personenbezogenen Daten in den folgenden Fällen weitergeben:</p>
          <ul>
            <li><strong>Mit Dienstleistern:</strong> Ich kann Ihre personenbezogenen Daten mit Dienstleistern teilen, um die Nutzung meines Dienstes zu überwachen und zu analysieren oder um Sie zu kontaktieren.</li>
            <li><strong>Mit Ihrer Zustimmung:</strong> Ich kann Ihre personenbezogenen Daten für jeden anderen Zweck offenlegen, wenn Sie dem zustimmen.</li>
          </ul>

          <h3>Aufbewahrung Ihrer personenbezogenen Daten</h3>
          <p>Ich werde Ihre personenbezogenen Daten nur so lange aufbewahren, wie es für die in dieser Datenschutzerklärung genannten Zwecke erforderlich ist. Ich werde Ihre personenbezogenen Daten aufbewahren und verwenden, soweit dies erforderlich ist, um gesetzlichen Verpflichtungen nachzukommen (z. B. wenn ich gesetzlich verpflichtet bin, Ihre Daten aufzubewahren), Streitigkeiten beizulegen und meine rechtlichen Vereinbarungen und Richtlinien durchzusetzen.</p>
          <p>Ich bewahre auch Nutzungsdaten zu internen Analysezwecken auf. Nutzungsdaten werden in der Regel für einen kürzeren Zeitraum gespeichert, es sei denn, diese Daten werden verwendet, um die Sicherheit zu stärken oder die Funktionalität meines Dienstes zu verbessern, oder ich bin gesetzlich verpflichtet, diese Daten länger aufzubewahren.</p>

          <h3>Übermittlung Ihrer personenbezogenen Daten</h3>
          <p>Ihre Informationen, einschließlich personenbezogener Daten, werden in meinen Geschäftsräumen und an anderen Orten verarbeitet, an denen die an der Verarbeitung beteiligten Parteien ansässig sind. Das bedeutet, dass diese Informationen an Computer außerhalb Ihres Bundeslands, Landes oder anderer staatlicher Zuständigkeiten übertragen und dort gespeichert werden können, wo andere Datenschutzgesetze gelten können als in Ihrer Zuständigkeit.</p>
          <p>Ihre Zustimmung zu dieser Datenschutzerklärung und Ihre Übermittlung solcher Informationen stellen Ihre Einwilligung zu dieser Übertragung dar.</p>
          <p>Ich werde alle angemessenen Schritte unternehmen, um sicherzustellen, dass Ihre Daten sicher und im Einklang mit dieser Datenschutzerklärung behandelt werden, und dass keine Übermittlung Ihrer personenbezogenen Daten an eine Organisation oder ein Land erfolgt, sofern keine angemessenen Schutzmaßnahmen vorhanden sind, einschließlich der Sicherheit Ihrer Daten und anderer personenbezogener Informationen.</p>

          <h3>Offenlegung Ihrer personenbezogenen Daten</h3>
          <h4>Strafverfolgung</h4>
          <p>Unter bestimmten Umständen kann ich verpflichtet sein, Ihre personenbezogenen Daten offenzulegen, wenn dies gesetzlich vorgeschrieben ist oder auf gültige Anfragen öffentlicher Behörden (z. B. eines Gerichts oder einer Regierungsbehörde) erfolgt.</p>
          <h4>Andere rechtliche Anforderungen</h4>
          <p>Ich kann Ihre personenbezogenen Daten in gutem Glauben offenlegen, wenn ich der Ansicht bin, dass eine solche Handlung erforderlich ist, um:</p>
          <ul>
            <li>einer gesetzlichen Verpflichtung nachzukommen</li>
            <li>meine Rechte oder mein Eigentum zu schützen oder zu verteidigen</li>
            <li>mögliches Fehlverhalten im Zusammenhang mit dem Dienst zu verhindern oder zu untersuchen</li>
            <li>die persönliche Sicherheit der Nutzer des Dienstes oder der Öffentlichkeit zu schützen</li>
            <li>vor rechtlicher Haftung zu schützen</li>
          </ul>

          <h3>Sicherheit Ihrer personenbezogenen Daten</h3>
          <p>Die Sicherheit Ihrer personenbezogenen Daten ist mir wichtig. Bitte beachten Sie jedoch, dass keine Methode der Übertragung über das Internet oder Methode der elektronischen Speicherung zu 100 % sicher ist. Obwohl ich bestrebt bin, wirtschaftlich angemessene Mittel zum Schutz Ihrer personenbezogenen Daten zu verwenden, kann ich keine absolute Sicherheit garantieren.</p>

          <h2>Datenschutz von Kindern</h2>
          <p>Mein Dienst richtet sich nicht an Personen unter 13 Jahren. Ich erfasse wissentlich keine personenbezogenen Daten von Personen unter 13 Jahren. Wenn Sie ein Elternteil oder Erziehungsberechtigter sind und Ihnen bekannt ist, dass Ihr Kind mir personenbezogene Daten zur Verfügung gestellt hat, kontaktieren Sie mich bitte. Wenn mir bekannt wird, dass ich personenbezogene Daten von Personen unter 13 Jahren ohne Zustimmung der Eltern erfasst habe, unternehme ich Schritte, um diese Informationen von meinen Servern zu löschen.</p>
          <p>Wenn ich mich auf eine Einwilligung als Rechtsgrundlage für die Verarbeitung Ihrer Informationen stütze und Ihr Land die Zustimmung eines Elternteils erfordert, kann ich die Zustimmung Ihrer Eltern einholen, bevor ich diese Informationen erfasse und verwende.</p>

          <h2>Links zu anderen Websites</h2>
          <p>Mein Dienst kann Links zu anderen Websites enthalten, die nicht von mir betrieben werden. Wenn Sie auf einen Link eines Drittanbieters klicken, werden Sie auf die Website dieses Drittanbieters weitergeleitet. Ich empfehle Ihnen dringend, die Datenschutzerklärung jeder Website, die Sie besuchen, zu lesen.</p>
          <p>Ich habe keine Kontrolle über und übernehme keine Verantwortung für den Inhalt, die Datenschutzrichtlinien oder -praktiken von Websites oder Diensten Dritter.</p>

          <h2>Änderungen an dieser Datenschutzerklärung</h2>
          <p>Ich kann meine Datenschutzerklärung von Zeit zu Zeit aktualisieren. Ich werde Sie über Änderungen informieren, indem ich die neue Datenschutzerklärung auf dieser Seite veröffentliche.</p>
          <p>Ich werde Sie per E-Mail und/oder durch einen deutlich sichtbaren Hinweis auf meinem Dienst über Änderungen informieren, bevor diese wirksam werden, und das Datum „Zuletzt aktualisiert“ oben in dieser Datenschutzerklärung anpassen.</p>
          <p>Sie sollten diese Datenschutzerklärung regelmäßig überprüfen, um sich über etwaige Änderungen zu informieren. Änderungen an dieser Datenschutzerklärung treten in Kraft, sobald sie auf dieser Seite veröffentlicht werden.</p>

          <h2>Kontakt</h2>
          <p>Wenn Sie Fragen zu dieser Datenschutzerklärung haben, können Sie mich kontaktieren:</p>
          <ul>
            <li><p>Per E-Mail: <a href="mailto:contact@fabianschuster.net">contact@fabianschuster.net</a></p></li>
            <li><p>Über diese Seite auf meiner Website: <Link href="/contact">https://www.fabianschuster.net/contact</Link></p></li>
          </ul>
        </div>
      </LanguageFilter>
    </Translation>
  );
});

export const head: DocumentHead = {
  title: 'Privacy Policy',
}